crscillitoe/RoboBanana

bot.py, db/__init__.py, db/channel_rewards.py, db/models.py
1. Add command to remove a previously configured reward via its name
2. Add `allow_redemptions`, `pause_redemptions` and `check_redemption_status` commands to ensure that channel rewards are only redeemable during stream
3. Only allow rewards to be redeemed if `cehck_redemption_status` is `True`
=> Remove Rewards and Pause Redemptions

bot.py
Commit titles summarize changes:
1. There was a bug where checking for the `Mod` role when closing a prediction did not return. This led to the prediction being closed even though the user did not have the correct permissions
2. Added command to refund a closed-but-not-complete prediction. This is a prediction where the `End Prediction` button has been pressed, but no payouts have been awarded.
3. Ensure that a prediction has been closed (i.e. `End Prediction` button has been pressed) before paying points out from `/hooj payout` or `/hooj refund_prediction`
=> Prediction Fixes

db/point_accrual.py
points column does not exist in MorningPoints. The correct column is weekly_count. Tested locally.
=> fix good morning points count

config.ini.example
During my initial setup, I discovered this variable was missing from the configuration example, simple commit to resolve potential issue with others.
=> Update config example with missing variable

bot.py, commands/mod_commands.py, commands/vod_commands.py
Currently, we’re hitting our maximum number of commands allowed for `/mod`. Refactor command tree to be grouped by function (i.e. `/prediction`, `/vod`, etc)
https://trello.com/c/oK0jGsmL
Ensured that updates are still published to server after changes
=> Pull vod-commands out into separate command Group

controllers/good_morning_controller.py
Christian wants to be able to do sub-only chat without users being required to do their Good Mornings in the stream chat. Remove stream-chat restriction on the command and lock the command to stream times
* Check if the interaction was created during the time window of 9:00AM and 11:30AM PST
* If yes, perform the Good Morning logic
* If no, respond to the interaction with an embedded datetime object for the user to understand when (in their timezone) they are allowed to use the command
=> Good morning can only occur between 9:00AM and 11:30AM PST

commands/reaction_commands.py, controllers/reaction_controller.py, db/__init__.py, db/emoji_reactions.py, db/models.py
Made in reference to issue #90 
Adds the /reactions set_emoji_reaction_delay {int} command.
This allows mods to set a timed delay in seconds for Robomoji reactions. Defaults to a delay of 15 seconds between reactions if not set. Records current datetime when Robonana reacts to a user's message and prevents further reactions until the delay has passed.
=> Added timed delay for Robomojis

commands/manager_commands.py
Fixed VOD command permissions to be usable by Mods (for administration/testing purposes), Community Managers, and the VOD Review Team
I don't believe this has been used elsewhere in the bot but `checks.has_any_role()` is actually quite useful for giving multiple roles access to the same command without the need for Role restructuring in the Discord or multiple commands. Good to keep in mind for future functionality.
=> VOD Command Perms

commands/manager_commands.py
I seem to have misread the documentation for `has_any_role`. Instead of passing a list of roles as a single argument, you are meant to pass each acceptable role individually as their own arguments. This should fix the `/manager` commands as currently they are not usable by anyone. Not sure how I didn't catch that in testing.
=> Manager Permission Fix

controllers/temprole_controller.py
Currently if the user does not have a given role and `/temprole extend` is used, it assigns the temprole expiration in the database, but does not actually give the user the role. This fixes this bug so that `/temprole extend` can be used to give roles without needing to first use `/temprole add`
=> Add role to user on /temprole extend

server/util/discord_client.py
Small PR that fixes the bug where ephemeral messages are published to the chat overlay
=> Don't show ephemeral messages in overlay

bot.py, controllers/good_morning_controller.py, controllers/temprole_controller.py
Closes #101 
Closes #102 
This PR adds a new config option for the channel in which the progress thread should be posted in.
Previously, this was the channel the command was executed in but without a command there is no inherent channel.
It also adds 2 new TIME variables with which to set when the role should expire and when the automatic distribution should take place.
With the current settings, roles are distributed at 11pm with an expiry of "upcoming sunday 11:30pm", making it so roles carry over seamlessly if the user achieved another GM reward. If not, the role simply expires at 11:30pm as it was planned.
The set_role method overrides any active temproles of the same role id, so this works without changes to said method.
Please excuse any code that doesn't follow Python conventions …
=> Implement automatic assignment of the GM role every sunday

commands/mod_commands.py, controllers/predictions/create_prediction_controller.py, controllers/predictions/prediction_entry_controller.py, controllers/predictions/update_prediction_controller.py, db/__init__.py, db/models.py, db/predictions.py, server/controllers/prediction_controller.py, views/predictions/create_predictions_modal.py
This Commit requires the DB to be migrated (regenerating the docker db volume is fine for testing too)
Added an optional "set_nickname" bool argument to the "start_prediction" command, defaulting to False.
When betting on a prediction, if "set_nickname" is true we prepend the users Username with the name of the choice they picked.
**It is recommended to upgrade to d.py 2.3.2+ with this commit, as we otherwise don't know of the existence of global Display Names and might set weird nicknames ("TAG username" instead of "TAG Display Name") (Doing this should also "fix" usernames being displayed on-stream rather then global Display Names). 
d.py 2.3.2 worked fine for my limited testing here and 2.1.0-->2.3.2 removed no features, so we should be fine.**
=> Add an optional arg to predictions to change Nicknames to reflect choice

controllers/predictions/payout_prediction_controller.py, views/predictions/prediction_vote_modal.py
This PR implements logic to statelessly revert a users nickname if they have bet in the prediction.
This happens whenever the prediction is paid out or refunded.
I also changed the original modal interaction to be deferred at the beginning of the method - this makes it so a "Robonana is thinking..." will appear in chat while we process our logic - we later edit this message with a followup.
Why do we do this? Discord grants us a maximum of 3 seconds to reply to an interaction and bets can and do exceed this limit.
Deferring increases the time we get to 15 seconds, which is why we do it here.
=> Implement nickname resets after predictions have been paid out or been refunded

config.example.yaml
These options aren't in the example file, however they do crash the bot when you try to start it.
=> Add config options missing from the example file

commands/connect_four.py, commands/manager_commands.py, commands/meme_commands.py, commands/mod_commands.py, commands/overlay_commands.py, commands/point_history_commands.py, commands/reaction_commands.py, commands/sync_commands.py, commands/temprole_commands.py, commands/vod_commands.py, config.example.yaml, controllers/temprole_controller.py
Bug fixed: Not providing a time indicator (s, m, etc.) on temprole commands no longer causes an exception
Also added Community Manager (Roles->CM) role and VOD Review Team (VODReview->ReviewerRole) to the config to use the IDs instead of magic strings
=> Stop using magic strings for command permission checks (+ small bugfix)

bot.py
As noted in #109, the accounting for custom emoji in messages made it so people can now spam emoji (e.g. [this](https://daark.de/8Bq0a)).
This PR implements a MAX_EMOJI_COUNT (custom) emoji limit, defaulting to 5.
I chose 5 because the 200 char limit used to trigger at about 5 emoji.
=> Implement an Emoji limit for messages in chat

commands/mod_commands.py
This PR enables 12 month tier 3 subscribers to start predictions in addition to the moderator ability to do so.
Line 284 of mod_commands.py can be altered to include 6moT3's/community managers by adding their role name to the list as well with no other changes.
This does allow the long term subs to flag the set nickname, which could be a pain.
Paying out and refunding predictions are still Mod exclusive.
=> Communal gambling

config.example.yaml
Missing 18MonthTier3Role (added in b90a8cd26154def9d46ec141530eb1d66c9019fa) crashes bot, add to config.example.yaml
=> add 18MonthTier3Role to config.example.yaml

commands/mod_commands.py, commands/prediction_commands.py, util/sync_utils.py
12+ month T3 subs can now run predictions, so moving the commands out of the mod domain makes sense.
This also allows better in-discord slash command permission management.
Furthermore, this increases the capacity for slash commands in the mod domain by the 5 we remove
=> Move prediction commands out of mod commands

views/predictions/create_predictions_modal.py
With 12 month subs being able to open predictions in any channel, I made it so the thread always gets posted in the raffle channel. It can otherwise get lost easily.
=> Post prediction thread in the prediction channel

commands/manager_commands.py, commands/mod_commands.py, commands/t3_commands.py
TTS defaults to enabled after each bot restart
This is V2 of this PR, which has the commands in the mod domain.
Since that space ONLY exists IN PR #128, this PR depends on said PR.
HOWEVER, **IMPORTANTLY**, this PR merges into the dev branch for 128 so this PR needs to be merged first if it is wanted in its current iteration. After that, PR 128 should be merged.
=> Add commands to enable/disable the T3 TTS redemption

bot.py
This prevents situations where a Mod TOs a user and the Crowdmute feature then lowers their TO duration to 10 minutes
=> Only apply crowdmute if the user is not TOd already

commands/viewer_commands.py
Adds a command to move pokemon. Uses ip  and a new port defined in the config file.
Response indicates success, which should inform user that their commands are not going through if used while pokemon is down. Responses are ephemeral, keeping chat clutter to a minimum.
=> Pokemon command

CHANGELOG.md, bot.py, controllers/temprole_controller.py, views/vod_submission/vod_submission_modal.py
- Add on_member_update event trigger which checks if roles are removed from the user.
- If the role is related to a temprole assigned to the user, the temprole is removed from the database.
- If the role is related to vod submissions, the vod submission entry is deleted from the database.
remove_role logic has been changed to a try-catch, where if it succeeds, it will delete the temprole log from the member update, but if it fails, it will delete it in the function itself.
=> Change temprole/vod submission DB deletion logic

db/point_accrual.py
`MIN_ACCRUAL_TIME` is actually 15 minutes, not 1 hour. I've updated the comment to use the variable instead, so that future changes won't make the comment outdated.
=> Update outdated point_accrual comment
