crscillitoe/RoboBanana

commands/mod_commands.py, requirements.txt
This reverts commit afc54eaec295575a59e74dec28f0a9df58d812a4.
=> Revert "art stuff"

bot.py, db/__init__.py
=> Fix DB singleton class to only create the engine once

bot.py, commands/mod_commands.py, controllers/prediction_controller.py, db/__init__.py, db/models.py, db/predictions.py
[Proof it's working](https://imgur.com/M9BAjqd)
=> Redo payout

bot.py, commands/mod_commands.py, commands/viewer_commands.py, controllers/good_morning_controller.py, db/__init__.py, db/point_accrual.py
https://user-images.githubusercontent.com/17772186/213013086-f78995af-0bf4-4d27-8c46-14c93683da47.mp4
https://user-images.githubusercontent.com/17772186/213013179-4423120f-c074-46ee-b70b-74b607614076.mp4
=> Rework Good Morning into command. Add good morning reset

commands/mod_commands.py, config.ini.example, controllers/good_morning_controller.py, db/__init__.py, db/good_morning.py, db/point_accrual.py
Assign configurable role to user if they've met the configured minimum number of streams
https://user-images.githubusercontent.com/17772186/213888301-92d1a118-7fb6-4812-9711-126f86db5ef8.mp4
Inform the mod if no one has earned the award
https://user-images.githubusercontent.com/17772186/213888379-682fdbe7-b93b-4f82-8c77-32c0fefb8f6d.mp4
UPDATE:
@Role rather than each individual user
=> Add command to reward viewers meeting 'good morning' threshold

commands/mod_commands.py, controllers/good_morning_controller.py, db/__init__.py, db/good_morning.py, db/models.py
Demo below!
https://user-images.githubusercontent.com/17772186/213948719-b088f2ad-69d5-44b7-b89a-e67398644207.mp4
=> Good Morning Reset Command + Total Count Column Addition

commands/mod_commands.py, controllers/good_morning_controller.py, db/__init__.py, db/good_morning.py
Add command to manually increment **ALL USERS'** good morning count by a specified number of points.
Table before and after running the increment command with value 5:
=> Add good-morning-increment command

controllers/prediction_controller.py
=> Prevent users from betting negative points

controllers/good_morning_controller.py
=> Create thread to track Good Morning Reward progress

commands/mod_commands.py, requirements.txt, server/server.py
Add support for direction optional argument to mod `timer` command. Timer will count up if set to `increment`.
There appear to be a lot of formatting changes so I'm not sure if we've been reliably running black on commits.
https://github.com/crscillitoe/RoboBananaFrontend/pull/7
=> Support timer counting up

commands/temprole_commands.py, controllers/temprole_controller.py, db/__init__.py, db/temproles.py, views/pagination/pagination_embed_view.py
Adds `/temprole view {role}` for https://github.com/crscillitoe/RoboBanana/issues/86
Potential bug: If a user has a permanent role and is assigned that role as a temprole it will be removed once the temprole expires
=> Add temprole view

bot.py
We now support adding emoji reactions through `/reactions toggle_emoji`
=> Remove hardcoded emoji reactions

controllers/predictions/create_prediction_controller.py, views/predictions/create_predictions_modal.py
Create a thread for each prediction, further interaction messages are then posted into that thread
Resolves: #93
=> Send predictions in threads

controllers/good_morning_controller.py
Suggested by LavFx at the start of the 15.01.2024 stream, potassium approved (https://youtu.be/vMksYYM4nI4?t=306)
(I asked Lav if they wanted to do the PR themselves, however they denied)
=> Update valid GM accrual time to 0830 to align with stream start time

bot.py
Change from message.content to message.clean_content, this makes sure channel mentions etc. get counted by the channel name, not the channel ID (which will always be 17-19, even for channels just called "faq" for example.
The regex I added checks for custom animated and regular emoji (hence the a?). Early IDs (2015) will be 17 numbers, older IDs will be 18 or 19 in length. We give a flat 20 int amount of leniency since checking for the exact amount is overkill.
The length added because we get the raw content is between 20-23 chars, so just subtracting 20 should be fine.
This will make emoji spam more possible, which is why another check for 4+ emoji or similar with the length check would be sensible - I didn't add it since this is already a PR w/o an Issue and I don't want to add more …
=> Check for custom emoji for message length and add leniency

controllers/predictions/prediction_entry_controller.py, views/predictions/prediction_vote_modal.py
(Yes I forgot about this yesterday because it's so simple x.x)
=> Don't cause an exception if the tag wouldn't fit into the existing name (@set_nickname for predictions)

commands/manager_commands.py, commands/mod_commands.py, config.example.yaml, views/predictions/close_prediction_view.py, views/predictions/create_predictions_modal.py
Updated #114 to include an audit channel.
=> Communal Gambling 2: Audit Channel Boogaloo

commands/t3_commands.py, views/rewards/redeem_tts_view.py
Requires https://github.com/crscillitoe/RoboBananaFrontend/pull/26 on the frontend
=> Allow overlay to display which persons voice was used

commands/manager_commands.py, commands/mod_commands.py, commands/t3_commands.py
Since that space ONLY exists IN PR #128, this PR depends on said PR.
HOWEVER, **IMPORTANTLY**, this PR currently merges into the dev branch for 128 so this PR needs to be merged first if it is wanted in its current iteration. After that, PR 128 should be merged.
=> Add command to temporarily set the cost of TTS (for special occasions)

commands/connect_four.py, commands/manager_commands.py, commands/marker_commands.py, commands/meme_commands.py, commands/mod_commands.py, commands/overlay_commands.py, commands/point_history_commands.py, commands/prediction_commands.py, commands/reaction_commands.py, commands/sync_commands.py, commands/temprole_commands.py, commands/vod_commands.py
IMPORTANT! This has hardcoded IDs and should be replaced when raze to radiant is over or config file changes are allowed. All files in this commit is affected by this.
=> Add hidden mod to mod commands

CHANGELOG.md, commands/marker_commands.py, commands/temprole_commands.py, compose-dev.yaml, controllers/vod_review_bank_controller.py, util/discord_utils.py
- Add auditing for /manager redeem command 
- Add what command was used in audit logs
- Change audit log user mentions to name + ID of user affected by command
- Change structure of audit logs to look better
=> Temprole log fixes and changes

CHANGELOG.md, bot.py, commands/mod_commands.py
Can be restricted to T3 and can grant a role optionally
=> Add command to get recently active chatters

commands/viewer_commands.py
Added support for moving more than one tile with one command. Allows user to add amount field, 1-9 inclusive.
=> Add pokemon multi move

bot.py, commands/reaction_commands.py, controllers/reaction_controller.py
- Disable crowd mute
- Enable crowd mute
- Set crowd mute emoji requirement amount
IMPORTANT!
This change requires /sync sync to show up to be used.
=> Add commands to configure crowd mute functionality

CHANGELOG.md, commands/reaction_commands.py
- Merge enable/disable command into one
- Rename "set_crowd_mute_limit" to "configure_crowd_mute" and added duration as an argument. 
IMPORTANT!
this requires /sync sync to be run once
=> Improve crowd mute commands

CHANGELOG.md, util/discord_utils.py
- Added defer function to discord_utils
- Modified reply function to support use of defer function
=> Add defer function and modify reply function in discord_utils

CHANGELOG.md, commands/mod_commands.py, commands/t3_commands.py
Works in tandem with https://github.com/crscillitoe/RoboBananaFrontend/pull/46
=> Implement commands to start emote animations

CHANGELOG.md, commands/viewer_commands.py
=> Re-enable vod submission
